# Generated by Django 2.2.2 on 2019-07-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_userteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='creator',
        ),
    ]
