# Generated by Django 2.2.4 on 2019-08-26 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_team_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_match', models.CharField(max_length=10, unique=True)),
                ('match_bet', models.CharField(max_length=1)),
                ('result', models.CharField(max_length=1)),
                ('odds_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bet_validate', models.BooleanField(default=False)),
                ('id_user_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.UserTeam', verbose_name='id of the user and his group')),
            ],
        ),
    ]
