# Generated by Django 2.2.4 on 2019-08-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_mybet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybet',
            name='result',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
