# Generated by Django 2.2.4 on 2019-08-26 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20190827_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybet',
            name='odds_value',
        ),
    ]
