# Generated by Django 2.2.4 on 2019-08-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_remove_mybet_odds_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteam',
            name='points',
            field=models.IntegerField(),
        ),
    ]
